/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as MarketingIndexRouteImport } from './routes/marketing.index'
import { Route as MarketingCampaignBuilderRouteImport } from './routes/marketing.campaign-builder'
import { Route as MarketingCampaignsRouteImport } from './routes/marketing.campaigns'
import { Route as MarketingContentRouteImport } from './routes/marketing.content'
import { Route as MarketingCreativesRouteImport } from './routes/marketing.creatives'
import { Route as MarketingOffersRouteImport } from './routes/marketing.offers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCampaignBuilderRoute =
  MarketingCampaignBuilderRouteImport.update({
    id: '/campaign-builder',
    path: '/campaign-builder',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingCampaignsRoute = MarketingCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContentRoute = MarketingContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCreativesRoute = MarketingCreativesRouteImport.update({
  id: '/creatives',
  path: '/creatives',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingOffersRoute = MarketingOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/marketing': typeof MarketingRouteWithChildren
  '/marketing/campaign-builder': typeof MarketingCampaignBuilderRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/content': typeof MarketingContentRoute
  '/marketing/creatives': typeof MarketingCreativesRoute
  '/marketing/offers': typeof MarketingOffersRoute
  '/marketing/': typeof MarketingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/marketing/campaign-builder': typeof MarketingCampaignBuilderRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/content': typeof MarketingContentRoute
  '/marketing/creatives': typeof MarketingCreativesRoute
  '/marketing/offers': typeof MarketingOffersRoute
  '/marketing': typeof MarketingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/marketing': typeof MarketingRouteWithChildren
  '/marketing/campaign-builder': typeof MarketingCampaignBuilderRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/content': typeof MarketingContentRoute
  '/marketing/creatives': typeof MarketingCreativesRoute
  '/marketing/offers': typeof MarketingOffersRoute
  '/marketing/': typeof MarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/marketing'
    | '/marketing/campaign-builder'
    | '/marketing/campaigns'
    | '/marketing/content'
    | '/marketing/creatives'
    | '/marketing/offers'
    | '/marketing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/marketing/campaign-builder'
    | '/marketing/campaigns'
    | '/marketing/content'
    | '/marketing/creatives'
    | '/marketing/offers'
    | '/marketing'
  id:
    | '__root__'
    | '/'
    | '/marketing'
    | '/marketing/campaign-builder'
    | '/marketing/campaigns'
    | '/marketing/content'
    | '/marketing/creatives'
    | '/marketing/offers'
    | '/marketing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketingRoute: typeof MarketingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/': {
      id: '/marketing/'
      path: '/'
      fullPath: '/marketing/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/campaign-builder': {
      id: '/marketing/campaign-builder'
      path: '/campaign-builder'
      fullPath: '/marketing/campaign-builder'
      preLoaderRoute: typeof MarketingCampaignBuilderRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/campaigns': {
      id: '/marketing/campaigns'
      path: '/campaigns'
      fullPath: '/marketing/campaigns'
      preLoaderRoute: typeof MarketingCampaignsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/content': {
      id: '/marketing/content'
      path: '/content'
      fullPath: '/marketing/content'
      preLoaderRoute: typeof MarketingContentRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/creatives': {
      id: '/marketing/creatives'
      path: '/creatives'
      fullPath: '/marketing/creatives'
      preLoaderRoute: typeof MarketingCreativesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/offers': {
      id: '/marketing/offers'
      path: '/offers'
      fullPath: '/marketing/offers'
      preLoaderRoute: typeof MarketingOffersRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingCampaignBuilderRoute: typeof MarketingCampaignBuilderRoute
  MarketingCampaignsRoute: typeof MarketingCampaignsRoute
  MarketingContentRoute: typeof MarketingContentRoute
  MarketingCreativesRoute: typeof MarketingCreativesRoute
  MarketingOffersRoute: typeof MarketingOffersRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingCampaignBuilderRoute: MarketingCampaignBuilderRoute,
  MarketingCampaignsRoute: MarketingCampaignsRoute,
  MarketingContentRoute: MarketingContentRoute,
  MarketingCreativesRoute: MarketingCreativesRoute,
  MarketingOffersRoute: MarketingOffersRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketingRoute: MarketingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
